= naum
:linkattrs:
:project-owner: aalmiray
:project-repo: kordamp
:project-name: naum

image:http://img.shields.io/travis/{project-owner}/{project-name}.svg["Build Status (travis)", link="https://travis-ci.org/{project-owner}/{project-name}"]
image:http://img.shields.io/coveralls/{project-owner}/{project-name}.svg["Coverage Status (coveralls)", link="https://coveralls.io/r/{project-owner}/{project-name}"]
image:http://img.shields.io/badge/license-ASL2-blue.svg["ASL2 Licensed", link="http://opensource.org/licenses/ASL2"]
image:https://api.bintray.com/packages/{project-owner}/{project-repo}/{project-name}/images/download.svg[link="https://bintray.com/{project-owner}/{project-repo}/{project-name}/_latestVersion"]

---

Naum is a tool that checks Java libraries for binary compatibility with previous releases.

== Installing

You can get the latest version of **naum** directly from link:https://bintray.com[Bintray's JCenter] repository.

Refer to the link:http://aalmiray.github.io/naum/[guide, window="_blank"] for further information on configuration
and usage.

== Building

You must meet the following requirements:

 * JDK8u40 as a minimum
 * Gradle 3.1

You may used the included gradle wrapper script if you don't have `gradle` installed.

=== Installing Gradle

.Manual

 . Download Gradle from http://gradle.org/downloads
 . Unzip the file into a directory without spaces (recommended).
 . Create a GRADLE_HOME environment variable that points to this directory.
 . Adjust your PATH environment variable to include $GRADLE_HOME/bin (%GRADLE_HOME%\bin on Windows).
 . Test your setup by invoking `gradle --version`.

.SDKMAN

 . Follow the instructions found at http://sdkman.io/ to install SDKMAN.
 . You need a POSIX environment if running Windows. We recommend using Babun Shell (http://babun.github.io/)
 . Once SDKMAN is installed invoke `sdk install gradle 3.1`.
 . Test your setup by invoking `gradle --version`.

.Gdub

GDub is a wrapper script that facilitates invoking gradle tasks anywhere within a Gradle project. It's smart enough
to use the gradle wrapper if available or your global gradle command. This is an optional download.

 . Follow the instructions found at https://github.com/dougborg/gdub to install gdub

=== Next Steps

Make a full build issuing `gradle build`.


=== IDE integration

.IntelliJ IDEA

 . To create an IntelliJ Idea project, run `./gradlew clean idea`
 . Make sure to install the Lombok plugin
 . Check that annotation processing is enabled (should be if you created the plugin with the above command).


